better autoheal

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 
 set -e
-# shellcheck disable=2039
 set -o pipefail
 
 DOCKER_SOCK=${DOCKER_SOCK:-/var/run/docker.sock}
@@ -10,16 +9,13 @@ CURL_TIMEOUT=${CURL_TIMEOUT:-30}
 
 # only use unix domain socket if no TCP endpoint is defined
 case "${DOCKER_SOCK}" in
-  "tcp://"*) HTTP_ENDPOINT="$(echo ${DOCKER_SOCK} | sed 's#tcp://#http://#')"
-             ;;
+  "tcp://"*) HTTP_ENDPOINT="$(echo ${DOCKER_SOCK} | sed 's#tcp://#http://#')" ;;
   "tcps://"*) HTTP_ENDPOINT="$(echo ${DOCKER_SOCK} | sed 's#tcps://#https://#')"
-             CA="--cacert /certs/ca.pem"
-             CLIENT_KEY="--key /certs/client-key.pem"
-             CLIENT_CERT="--cert /certs/client-cert.pem"
-             ;;
-  *)         HTTP_ENDPOINT="http://localhost"
-             UNIX_SOCK="--unix-socket ${DOCKER_SOCK}"
-             ;;
+              CA="--cacert /certs/ca.pem"
+              CLIENT_KEY="--key /certs/client-key.pem"
+              CLIENT_CERT="--cert /certs/client-cert.pem" ;;
+  *)          HTTP_ENDPOINT="http://localhost"
+              UNIX_SOCK="--unix-socket ${DOCKER_SOCK}" ;;
 esac
 
 AUTOHEAL_CONTAINER_LABEL=${AUTOHEAL_CONTAINER_LABEL:-autoheal}
@@ -34,14 +30,11 @@ docker_curl() {
   "$@"
 }
 
-# shellcheck disable=2039
 get_container_info() {
   local label_filter
   local url
 
-  # Set container selector
-  if [[ "$AUTOHEAL_CONTAINER_LABEL" = "all" ]]
-  then
+  if [[ "$AUTOHEAL_CONTAINER_LABEL" = "all" ]]; then
     label_filter=""
   else
     label_filter=",\"label\":\[\"${AUTOHEAL_CONTAINER_LABEL}=true\"\]"
@@ -50,60 +43,50 @@ get_container_info() {
   docker_curl "$url"
 }
 
-# shellcheck disable=2039
 restart_container() {
   local container_id="$1"
   local timeout="$2"
 
-  docker_curl -f -X POST "${HTTP_ENDPOINT}/containers/${container_id}/restart?t=${timeout}"
+  if ! docker_curl -f -X POST "${HTTP_ENDPOINT}/containers/${container_id}/restart?t=${timeout}"; then
+    echo "$(date +%d-%m-%Y" "%H:%M:%S) Restarting container ${container_id:0:12} failed" >&2
+  fi
 }
 
-# SIGTERM-handler
 term_handler() {
-  exit 143  # 128 + 15 -- SIGTERM
+  exit 143
 }
 
-# shellcheck disable=2039
-trap 'kill $$; term_handler' SIGTERM
+trap 'term_handler' SIGTERM
 
 if [[ "$1" = "autoheal" ]]; then
-  if [[ -n "$UNIX_SOCK" ]] && ! [[ -S "$DOCKER_SOCK" ]]
-  then
+  if [[ -n "$UNIX_SOCK" ]] && ! [[ -S "$DOCKER_SOCK" ]]; then
     echo "unix socket is currently not available" >&2
     exit 1
   fi
-  # Delayed startup
-  if [[ "$AUTOHEAL_START_PERIOD" -gt 0 ]]
-  then
-  echo "Monitoring containers for unhealthy status in $AUTOHEAL_START_PERIOD second(s)"
+
+  if [[ "$AUTOHEAL_START_PERIOD" -gt 0 ]]; then
+    echo "Monitoring containers for unhealthy status in $AUTOHEAL_START_PERIOD second(s)"
     sleep "$AUTOHEAL_START_PERIOD"
   fi
 
-  while true
-  do
+  while true; do
     STOP_TIMEOUT=".Labels[\"autoheal.stop.timeout\"] // $AUTOHEAL_DEFAULT_STOP_TIMEOUT"
-    get_container_info | \
-      jq -r "foreach .[] as \$CONTAINER([];[]; \$CONTAINER | .Id, .Names[0], .State, ${STOP_TIMEOUT})" | \
-      while read -r CONTAINER_ID && read -r CONTAINER_NAME && read -r CONTAINER_STATE && read -r TIMEOUT
-    do
-      # shellcheck disable=2039
+    if ! get_container_info | jq -r "foreach .[] as \$CONTAINER([];[]; \$CONTAINER | .Id, .Names[0], .State, ${STOP_TIMEOUT})" | while read -r CONTAINER_ID && read -r CONTAINER_NAME && read -r CONTAINER_STATE && read -r TIMEOUT; do
       CONTAINER_SHORT_ID=${CONTAINER_ID:0:12}
       DATE=$(date +%d-%m-%Y" "%H:%M:%S)
 
-      if [[ "$CONTAINER_NAME" = "null" ]]
-      then
+      if [[ "$CONTAINER_NAME" = "null" ]]; then
         echo "$DATE Container name of (${CONTAINER_SHORT_ID}) is null, which implies container does not exist - don't restart" >&2
-      elif [[ "$CONTAINER_STATE" = "restarting" ]]
-      then
+      elif [[ "$CONTAINER_STATE" = "restarting" ]]; then
         echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be restarting - don't restart"
       else
         echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be unhealthy - Restarting container now with ${TIMEOUT}s timeout"
-        if ! restart_container "$CONTAINER_ID" "$TIMEOUT"
-        then
-          echo "$DATE Restarting container $CONTAINER_SHORT_ID failed" >&2
-        fi
+        restart_container "$CONTAINER_ID" "$TIMEOUT"
       fi
-    done
+    done; then
+      echo "$(date +%d-%m-%Y" "%H:%M:%S) Error processing container info" >&2
+    fi
+
     sleep "$AUTOHEAL_INTERVAL"
   done
 
